FROM spark:python3

RUN apt-get update
RUN apt install -y python3 python3-pip
RUN pip install --upgrade pip setuptools --user
RUN rm -r /root/.cache && rm -rf /var/cache/apt/*

WORKDIR /opt/application
COPY requirements.txt .
COPY pipeline.py /pipeline.py

RUN pip install --no-cache-dir  -r requirements.txt --user

CMD [ "python3","pipeline.py" ]
