version: "3.8"

services:
  notebook:
    image: jupyter/all-spark-notebook
    container_name: spark-notebook
    ports:
      - 8888:8888
      - 4040:4040
    environment:
      - JUPYTER_TOKEN=etldata
    restart: unless-stopped
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    networks:
      - etl_networks

  lake-cassandra:
    image: cassandra:latest
    container_name: cassandra-datalake
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=datalake
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra/data
    networks:
      - etl_networks

  ware_mysql:
    image: mysql:latest
    container_name: mysql_data_warehouse
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=warehouse
      - TZ="Asia/Ho_Chi_Minh"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - etl_networks

networks:
  etl_networks:
    driver: bridge
    name: etl_networks

volumes:
  cassandra_data:
  mysql_data:
